// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdaJEdF9BnPSu6HICKf5QUhVEWeetdGbA',
    appId: '1:911926943613:web:704026083bf669a28d7614',
    messagingSenderId: '911926943613',
    projectId: 'flutter-reddit-02',
    authDomain: 'flutter-reddit-02.firebaseapp.com',
    storageBucket: 'flutter-reddit-02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBztP6H5mRHiQ_7Etbr9YJTnmsWhYKLj0w',
    appId: '1:911926943613:android:477498973994ff268d7614',
    messagingSenderId: '911926943613',
    projectId: 'flutter-reddit-02',
    storageBucket: 'flutter-reddit-02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJnb5ZQrGLgIKNDSBzf5jwE4aNS0kXTE',
    appId: '1:911926943613:ios:bfa2a92f0bbb912d8d7614',
    messagingSenderId: '911926943613',
    projectId: 'flutter-reddit-02',
    storageBucket: 'flutter-reddit-02.appspot.com',
    iosClientId: '911926943613-otnqefqrt2mcaaiqgb8n4l37ek8q7puk.apps.googleusercontent.com',
    iosBundleId: 'com.cromdev.flutterReddit',
  );
}
